import { useState, useEffect, useRef, useImperativeHandle, forwardRef, KeyboardEvent } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { useCodingAssistant } from '../../hooks/useCodingAssistant';
import { openWorkspace } from '../../api/files';
import { UIMessage, UIBlock } from '../../types';
import { PROVIDERS } from '../../providers';
import type { Provider } from '../../providers';
import type { FileNode } from '../../types';

const API_BASE = import.meta.env.DEV ? 'http://localhost:3001' : '';

function argumentSummary(input: unknown): string | null {
  if (!input || typeof input !== 'object') return null;
  const values = Object.values(input as Record<string, unknown>);
  const path = values.find(value => typeof value === 'string' && value.includes('/')) as string | undefined;
  if (!path) return null;
  const parts = path.split('/').filter(Boolean);
  return parts.length > 1 ? parts[parts.length - 2] + '/' + parts[parts.length - 1] : parts[0] ?? null;
}

function ToolBlock({ block }: { block: UIBlock & { type: 'tool' } }) {
  const [expanded, setExpanded] = useState(false);
  const inputStr = JSON.stringify(block.input, null, 2);
  const pathLabel = argumentSummary(block.input);
  return (
    <div style={{ background: 'var(--color-bg-subtle)', border: '1px solid var(--color-border)', borderRadius: 6, marginBottom: 6, overflow: 'hidden' }}>
      <button onClick={() => setExpanded(e => !e)} style={{ width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '7px 12px', background: 'none', border: 'none', cursor: 'pointer', color: 'var(--color-text-secondary)', fontSize: 11, textAlign: 'left' }}>
        <span style={{ display: 'flex', alignItems: 'center', gap: 7, minWidth: 0 }}>
          <span style={{ width: 16, height: 16, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', borderRadius: '50%', background: block.pending ? '#e7c54720' : block.error ? '#f4877120' : '#4ec9b020', color: block.pending ? '#e7c547' : block.error ? '#f48771' : '#4ec9b0', fontSize: 10, fontWeight: 700 }}>{block.pending ? '…' : block.error ? '✕' : '✓'}</span>
          <span style={{ fontFamily: 'monospace', fontWeight: 600 }}>{block.name}</span>
          {pathLabel && <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', color: 'var(--color-text-primary)' }}>· {pathLabel}</span>}
          {block.pending && <span style={{ fontSize: 10, fontStyle: 'italic' }}>running…</span>}
        </span>
        <span style={{ fontSize: 10, flexShrink: 0 }}>{expanded ? '▲' : '▼'}</span>
      </button>
      {expanded && <div style={{ padding: '0 12px 10px', fontSize: 11, fontFamily: 'monospace' }}><div style={{ color: 'var(--color-text-secondary)', marginBottom: 4 }}>Arguments:</div><pre style={{ margin: 0, padding: '7px 8px', background: 'var(--color-bg-editor)', border: '1px solid var(--color-border)', borderRadius: 5, whiteSpace: 'pre-wrap', wordBreak: 'break-all', color: 'var(--color-text-primary)', fontSize: 10 }}>{inputStr}</pre>{block.result !== undefined && <><div style={{ color: 'var(--color-text-secondary)', marginTop: 8, marginBottom: 4 }}>{block.error ? 'Error:' : 'Output:'}</div><pre style={{ margin: 0, padding: '7px 8px', background: 'var(--color-bg-code)', border: '1px solid var(--color-border)', borderRadius: 5, whiteSpace: 'pre-wrap', wordBreak: 'break-all', color: block.error ? '#f48771' : 'var(--color-text-primary)', fontSize: 10, maxHeight: 220, overflowY: 'auto' }}>{block.result}</pre></>}</div>}
    </div>
  );
}

function ThoughtBlock({ block }: { block: UIBlock & { type: 'thought' } }) {
  return <div style={{ background: 'var(--color-bg-subtler)', borderLeft: '3px solid #4fc1ff', borderRadius: 6, padding: '6px 10px', marginBottom: 6, fontSize: 12, fontStyle: 'italic', color: 'var(--color-text-secondary)', whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>{block.content}</div>;
}

function CommandApprovalBlock({ block, onApprove, onReject }: { block: UIBlock & { type: 'command-approval' }; onApprove: () => void; onReject: () => void }) {
  const outputRef = useRef<HTMLPreElement>(null);
  const isPending = block.status === 'pending';
  const isApproved = block.status === 'approved';
  useEffect(() => { if (outputRef.current) outputRef.current.scrollTop = outputRef.current.scrollHeight; }, [block.output]);
  const borderColor = isPending ? '#e7c54760' : isApproved ? '#4ec9b040' : '#f4877140';
  const statusColor = isPending ? '#e7c547' : isApproved ? '#4ec9b0' : '#f48771';
  const statusBg = isPending ? '#e7c54720' : isApproved ? '#4ec9b020' : '#f4877120';
  return <div style={{ background: 'var(--color-bg-subtle)', border: `1px solid ${borderColor}`, borderRadius: 6, marginBottom: 8, overflow: 'hidden' }}><div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '7px 10px', background: 'var(--color-bg-subtler)', borderBottom: '1px solid var(--color-border)' }}><span style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 11 }}><span>⚡</span><span style={{ fontWeight: 600 }}>Terminal command</span></span><span style={{ fontSize: 10, color: statusColor, background: statusBg, border: `1px solid ${statusColor}40`, borderRadius: 999, padding: '2px 7px' }}>{isPending ? 'waiting for approval' : isApproved ? 'approved' : 'rejected'}</span></div><div style={{ padding: '8px 10px' }}><div style={{ fontSize: 11, color: 'var(--color-text-secondary)', marginBottom: 5 }}>{block.reason}</div><pre style={{ margin: '0 0 6px', padding: '7px 9px', background: 'var(--color-bg-editor)', border: '1px solid var(--color-border)', borderRadius: 5, fontSize: 12, fontFamily: 'monospace', color: 'var(--color-code-text)', whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>$ {block.command}</pre>{block.cwd && <div style={{ fontSize: 10, color: 'var(--color-text-secondary)', marginBottom: 6 }}>in {block.cwd}</div>}{isPending && <div style={{ display: 'flex', gap: 6, marginTop: 4 }}><button onClick={onApprove} style={{ background: '#1e4a1e', border: '1px solid #4ec9b060', borderRadius: 999, color: '#4ec9b0', fontSize: 11, padding: '5px 13px', cursor: 'pointer', fontWeight: 600 }}>✓ Approve</button><button onClick={onReject} style={{ background: 'none', border: '1px solid var(--color-border)', borderRadius: 999, color: 'var(--color-text-secondary)', fontSize: 11, padding: '5px 13px', cursor: 'pointer' }}>✕ Reject</button></div>}{block.output && <pre ref={outputRef} style={{ marginTop: 8, padding: '7px 9px', background: 'var(--color-bg-code)', border: '1px solid var(--color-border)', borderRadius: 5, fontSize: 11, fontFamily: 'monospace', color: 'var(--color-text-primary)', whiteSpace: 'pre-wrap', wordBreak: 'break-all', maxHeight: 220, overflowY: 'auto' }}>{block.output}</pre>}</div></div>;
}

function MessageBubble({ msg, isLast, sendApproval, onSuggestion }: { msg: UIMessage; isLast: boolean; sendApproval: (id: string, approved: boolean) => void; onSuggestion: (text: string) => void }) {
  if (msg.role === 'user') return <div style={{ marginBottom: 12 }}><div style={{ fontSize: 11, color: 'var(--color-text-secondary)', marginBottom: 4, fontWeight: 600 }}>You</div><div style={{ background: 'var(--color-bg-user-bubble)', border: '1px solid var(--color-border)', borderRadius: 16, padding: '8px 10px', fontSize: 13, color: 'var(--color-text-primary)', whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>{msg.content}</div></div>;
  const isStreaming = msg.isStreaming;
  const hasFileTool = msg.blocks.some(block => block.type === 'tool' && (block.name === 'read_file' || block.name === 'write_file'));
  return <div style={{ marginBottom: 12 }}><div style={{ fontSize: 11, color: 'var(--color-text-secondary)', marginBottom: 4, fontWeight: 600, display: 'flex', alignItems: 'center', gap: 5 }}><img src="/logo.png" alt="Iodine" style={{ width: 14, height: 14, objectFit: 'contain' }} />Assistant</div><div>{msg.blocks.map((block, i) => { if (block.type === 'text') { const showCursor = isStreaming && isLast && i === msg.blocks.length - 1; return <div key={i} className="md-body"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{ code({ className, children, ...props }) { const isBlock = className?.startsWith('language-'); return isBlock ? <pre className="md-pre"><code className={className} {...props}>{children}</code></pre> : <code className="md-code-inline" {...props}>{children}</code>; } }}>{block.content}</ReactMarkdown>{showCursor && <span style={{ animation: 'blink 1s step-end infinite', opacity: 1 }}>▌</span>}</div>; } if (block.type === 'thought') return <ThoughtBlock key={i} block={block} />; if (block.type === 'command-approval') return <CommandApprovalBlock key={block.id} block={block} onApprove={() => sendApproval(block.id, true)} onReject={() => sendApproval(block.id, false)} />; return <ToolBlock key={block.id} block={block} />; })}{hasFileTool && !isStreaming && <button onClick={() => onSuggestion('Open file for me')} style={{ background: 'var(--color-bg-subtle)', border: '1px solid var(--color-border)', borderRadius: 999, color: 'var(--color-text-secondary)', cursor: 'pointer', fontSize: 11, padding: '5px 10px', marginTop: 4 }}>Open file for me</button>}{isStreaming && msg.blocks.length === 0 && <span style={{ fontSize: 13, color: 'var(--color-text-secondary)', animation: 'blink 1s step-end infinite' }}>▌</span>}</div></div>;
}

export interface CodingAssistantHandle {
  injectProactiveMessage: (message: string, collectContext: () => Promise<string>) => void;
  notifyEditorActivity: () => void;
}
interface CodingAssistantProps { workspacePath: string | null; activeFilePath: string | null; onWorkspaceOpen: (path: string) => void; provider: Provider; model: string; setProvider: (id: string) => void; setModel: (id: string) => void; getEditorContext?: () => string | null; contextNodes: FileNode[]; onRemoveContextNode: (path: string) => void; onClearContextNodes: () => void; onNavigateToLine?: (filePath: string, line: number, endLine?: number, startCol?: number, endCol?: number) => void; onOpenNode?: (nodeName: string, nodeId?: string) => void; activeSystemNode?: string | null; onUserTyping?: () => void; onMessageSent?: () => void; onWatchTrigger?: () => void; }

export const CodingAssistant = forwardRef<CodingAssistantHandle, CodingAssistantProps>(function CodingAssistant({ workspacePath, activeFilePath, onWorkspaceOpen, provider, model, setProvider, setModel, getEditorContext, contextNodes, onRemoveContextNode, onClearContextNodes, onNavigateToLine, onOpenNode, activeSystemNode, onUserTyping, onMessageSent, onWatchTrigger }, ref) {
  const { uiMessages, isLoading, isWatching, sendMessage, stopExecution, clearMessages, sendApproval, injectProactiveMessage, notifyEditorActivity } = useCodingAssistant(provider, model, onNavigateToLine, onWatchTrigger);
  useImperativeHandle(ref, () => ({ injectProactiveMessage, notifyEditorActivity }), [injectProactiveMessage, notifyEditorActivity]);
  const [input, setInput] = useState(''); const [isTutorMode, setIsTutorMode] = useState(false); const [providerStatus, setProviderStatus] = useState<Record<string, boolean>>({}); const [showHelp, setShowHelp] = useState(false); const apiConfigured = providerStatus[provider.id] ?? null; const [wsInput, setWsInput] = useState(''); const [wsOpening, setWsOpening] = useState(false); const [wsError, setWsError] = useState<string | null>(null); const scrollRef = useRef<HTMLDivElement>(null);
  useEffect(() => { fetch(`${API_BASE}/api/agent/status`, { method: 'GET' }).then(r => r.json()).then(data => setProviderStatus(data.providers ?? { anthropic: data.configured })).catch(() => setProviderStatus({})); }, []);
  const handleSetWorkspace = async () => { if (!wsInput.trim()) return; setWsOpening(true); setWsError(null); try { const result = await openWorkspace(wsInput.trim()); if (result.path) { onWorkspaceOpen(result.path); setWsInput(''); } } catch (err) { setWsError(err instanceof Error ? err.message : 'Failed to open folder'); } finally { setWsOpening(false); } };
  useEffect(() => { if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight; }, [uiMessages]);
  const handleSend = () => { const text = input.trim(); if (!text || isLoading) return; setInput(''); const editorContext = getEditorContext?.() ?? null; const ctxPaths = contextNodes.map(n => !workspacePath ? n.path : n.path.startsWith(workspacePath + '/') ? n.path.slice(workspacePath.length + 1) : n.path); onClearContextNodes(); sendMessage(text, activeFilePath, editorContext, ctxPaths.length > 0 ? ctxPaths : undefined, isTutorMode); onMessageSent?.(); };
  const handleSuggestion = (text: string) => { setInput(text); onUserTyping?.(); };
  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleSend(); } };
  return <div className={isWatching ? 'assistant-panel assistant-panel-attention' : 'assistant-panel'} style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}><style>{`@keyframes blink { 0%, 100% { opacity: 1; } 50% { opacity: 0; } } @keyframes watching-pulse { 0%, 100% { opacity: .4; transform: scale(.8); } 50% { opacity: 1; transform: scale(1.15); } } @keyframes assistant-attention { 0%, 100% { box-shadow: inset 0 0 0 1px #e7c54770, 0 0 0 0 #e7c54700, 0 0 10px #e7c54745; } 50% { box-shadow: inset 0 0 0 2px #e7c547, 0 0 0 7px #e7c54735, 0 0 30px #e7c547aa; } } .assistant-panel-attention { animation: assistant-attention 1.15s ease-in-out infinite; } .watching-dot { display:inline-block; width:10px; height:10px; border-radius:50%; background:#e7c547; box-shadow:0 0 0 3px #e7c54745, 0 0 14px #e7c547; animation:watching-pulse .7s ease-in-out infinite; flex-shrink:0; } .watching-alert { color:#e7c547; font-weight:700; font-style:normal; text-shadow:0 0 8px #e7c54780; } .md-body { font-size:13px; color:var(--color-text-primary); line-height:1.6; word-break:break-word; margin-bottom:4px; } .md-body > *:first-child { margin-top:0; } .md-body > *:last-child { margin-bottom:0; } .md-body h1,.md-body h2,.md-body h3,.md-body h4 { font-weight:600; margin:10px 0 4px; } .md-body h1 { font-size:16px; } .md-body h2 { font-size:14px; } .md-body h3,.md-body h4 { font-size:13px; } .md-body p { margin:4px 0; } .md-body ul,.md-body ol { margin:4px 0; padding-left:18px; } .md-body li { margin:2px 0; } .md-body strong { font-weight:600; } .md-body em { font-style:italic; } .md-body blockquote { border-left:3px solid var(--color-border); margin:6px 0; padding:2px 10px; color:var(--color-text-secondary); } .md-body hr { border:none; border-top:1px solid var(--color-border); margin:8px 0; } .md-body a { color:#4fc1ff; text-decoration:underline; } .md-body table { border-collapse:collapse; font-size:12px; margin:6px 0; width:100%; } .md-body th,.md-body td { border:1px solid var(--color-border); padding:4px 8px; text-align:left; } .md-body th { background:#ffffff0a; font-weight:600; } .md-pre { background:var(--color-bg-editor); border:1px solid var(--color-border); border-radius:5px; padding:8px 10px; overflow-x:auto; margin:6px 0; font-size:12px; font-family:monospace; white-space:pre; } .md-code-inline { background:#ffffff12; border-radius:5px; padding:1px 4px; font-size:12px; font-family:monospace; }`}</style>
      <div style={{ display: 'flex', alignItems: 'center', padding: '0 10px', borderBottom: showHelp ? 'none' : '1px solid var(--color-border)', flexShrink: 0, gap: 6, height: 36 }}>
        {PROVIDERS.length === 1 ? <span style={{ fontSize: 11, color: 'var(--color-text-secondary)', flexShrink: 0 }}>{provider.label}</span> : <select value={provider.id} onChange={e => setProvider(e.target.value)} style={{ background: 'var(--color-bg-sidebar)', border: '1px solid var(--color-border)', borderRadius: 6, color: 'var(--color-text-primary)', fontSize: 11, padding: '2px 6px', cursor: 'pointer' }}>{PROVIDERS.map(p => <option key={p.id} value={p.id}>{p.label}</option>)}</select>}
        <select value={model} onChange={e => setModel(e.target.value)} style={{ flex: 1, minWidth: 0, background: 'var(--color-bg-sidebar)', border: '1px solid var(--color-border)', borderRadius: 6, color: 'var(--color-text-primary)', fontSize: 11, padding: '2px 6px', cursor: 'pointer' }}>{provider.models.map(m => <option key={m.id} value={m.id}>{m.label}</option>)}</select>
        <button onClick={() => setShowHelp(v => !v)} title="API key setup" style={{ width: 18, height: 18, borderRadius: '50%', border: '1px solid var(--color-border)', background: showHelp ? 'var(--color-bg-hover)' : 'none', color: 'var(--color-text-secondary)', fontSize: 11, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, fontWeight: 600, lineHeight: 1 }}>?</button>
        {uiMessages.length > 0 && <button onClick={clearMessages} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--color-text-secondary)', fontSize: 10, padding: '2px 4px', flexShrink: 0 }} title="Clear chat">✕</button>}
      </div>
      {showHelp && <div style={{ margin: 0, padding: '10px 12px', background: 'var(--color-bg-subtle)', borderBottom: '1px solid var(--color-border)', fontSize: 12, flexShrink: 0 }}><div style={{ fontWeight: 600, color: 'var(--color-text-primary)', marginBottom: 6 }}>{provider.setupTitle}</div><pre style={{ margin: 0, whiteSpace: 'pre-wrap', fontFamily: 'inherit', color: 'var(--color-text-secondary)', fontSize: 12, lineHeight: 1.6 }}>{provider.setupInstructions}</pre></div>}
      {apiConfigured === false && <div style={{ margin: '8px 8px 0', padding: '8px 10px', background: '#f487710a', border: '1px solid #f4877140', borderRadius: 4, fontSize: 12, color: '#f48771', flexShrink: 0 }}>No {provider.label} API key configured. Click <strong>?</strong> above for setup instructions.</div>}
      {apiConfigured === true && !workspacePath && <div style={{ margin: '8px 8px 0', padding: '8px 10px', background: '#e7c5470a', border: '1px solid #e7c54740', borderRadius: 4, fontSize: 12, color: '#e7c547', flexShrink: 0 }}><div style={{ marginBottom: 6 }}>No workspace set. Enter an absolute path so the assistant can read and write files.</div><div style={{ display: 'flex', gap: 6 }}><input type="text" value={wsInput} onChange={e => setWsInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') handleSetWorkspace(); }} placeholder="/absolute/path/to/project" style={{ flex: 1, background: 'var(--color-bg-input)', border: '1px solid #e7c54760', borderRadius: 6, color: 'var(--color-text-primary)', padding: '4px 8px', fontSize: 12, outline: 'none' }} /><button onClick={handleSetWorkspace} disabled={wsOpening || !wsInput.trim()} style={{ background: '#e7c547', color: '#1e1e1e', borderRadius: 999, padding: '4px 10px', fontSize: 12, fontWeight: 600, cursor: wsOpening || !wsInput.trim() ? 'default' : 'pointer', opacity: wsOpening || !wsInput.trim() ? .6 : 1 }}>{wsOpening ? '…' : 'Open'}</button></div>{wsError && <div style={{ marginTop: 4, color: '#f48771', fontSize: 11 }}>{wsError}</div>}</div>}
      {workspacePath && <div style={{ margin: '6px 8px 0', padding: '4px 8px', background: 'var(--color-bg-subtle)', border: '1px solid var(--color-border)', borderRadius: 6, fontSize: 11, color: 'var(--color-text-secondary)', flexShrink: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }} title={workspacePath}>{workspacePath}</div>}
      <div ref={scrollRef} style={{ flex: 1, overflowY: 'auto', padding: '12px 10px' }}>{uiMessages.length === 0 && <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', gap: 8, color: 'var(--color-text-secondary)', textAlign: 'center' }}><svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" style={{ opacity: .4 }}><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2 2z" /></svg><p style={{ fontSize: 12, margin: 0 }}>Ask about your code</p></div>}{uiMessages.map((msg, i) => <MessageBubble key={msg.id} msg={msg} isLast={i === uiMessages.length - 1} sendApproval={sendApproval} onSuggestion={handleSuggestion} />)}</div>
      <div style={{ borderTop: '1px solid var(--color-border)', padding: '8px 10px', display: 'flex', flexDirection: 'column', gap: 6, flexShrink: 0 }}>
        {activeSystemNode && onOpenNode && <button onClick={() => onOpenNode(activeSystemNode)} title="Navigate to this node in System View" style={{ alignSelf: 'flex-start', display: 'inline-flex', alignItems: 'center', gap: 5, background: 'transparent', border: '1px solid var(--color-accent, #0e639c)', borderRadius: 999, padding: '2px 8px', fontSize: 11, color: 'var(--color-accent, #0e639c)', cursor: 'pointer', flexShrink: 0 }}>◎ {activeSystemNode}</button>}
        {contextNodes.length > 0 && <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>{contextNodes.map(node => <div key={node.path} style={{ display: 'flex', alignItems: 'center', gap: 3, background: 'var(--color-bg-subtle)', border: '1px solid var(--color-border)', borderRadius: 999, padding: '2px 6px 2px 7px', fontSize: 11, color: 'var(--color-text-secondary)', maxWidth: '100%' }}><span style={{ fontSize: 10, flexShrink: 0 }}>{node.type === 'directory' ? '📁' : '📄'}</span><span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{node.name}</span><button onClick={() => onRemoveContextNode(node.path)} title="Remove from context" style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--color-text-secondary)', fontSize: 12, lineHeight: 1, padding: '0 1px', flexShrink: 0 }}>×</button></div>)}</div>}
        {isWatching && <div className="watching-alert" style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 12, padding: '7px 10px', border: '1px solid #e7c547', borderRadius: 6, background: '#e7c54718' }}><span className="watching-dot" />Assistant is actively watching your progress</div>}
        <textarea value={input} onChange={e => { setInput(e.target.value); onUserTyping?.(); }} onKeyDown={handleKeyDown} placeholder="Ask anything… (Enter to send, Shift+Enter for newline)" rows={3} disabled={isLoading} style={{ background: '#1a1a1a', border: '1px solid var(--color-border)', borderRadius: 10, color: 'var(--color-text-primary)', fontSize: 12, padding: '9px 11px', resize: 'none', fontFamily: 'inherit', outline: 'none', width: '100%', boxSizing: 'border-box' }} />
        <div style={{ alignSelf: 'flex-end', display: 'flex', gap: 6, alignItems: 'center' }}><button onClick={() => setIsTutorMode(v => !v)} title={isTutorMode ? 'Tutor Mode on — AI will guide without editing' : 'Enable Tutor Mode'} style={{ background: isTutorMode ? '#1e4d2e' : 'none', border: `1px solid ${isTutorMode ? '#4ec9b060' : 'var(--color-border)'}`, borderRadius: 999, color: isTutorMode ? '#4ec9b0' : 'var(--color-text-secondary)', cursor: 'pointer', fontSize: 11, padding: '5px 11px', fontWeight: isTutorMode ? 600 : 400 }}>Tutor</button>{isLoading && <button onClick={stopExecution} style={{ background: '#f4877118', border: '1px solid #f4877160', borderRadius: 999, color: '#f48771', cursor: 'pointer', fontSize: 12, padding: '5px 14px', fontWeight: 600 }}>Stop</button>}<button onClick={handleSend} disabled={isLoading || !input.trim()} style={{ background: isLoading || !input.trim() ? '#ffffff18' : '#0e639c', border: 'none', borderRadius: 999, color: isLoading || !input.trim() ? 'var(--color-text-secondary)' : '#fff', cursor: isLoading || !input.trim() ? 'default' : 'pointer', fontSize: 12, padding: '5px 15px', fontWeight: 600 }}>{isLoading ? 'Thinking…' : 'Send'}</button></div>
      </div>
    </div>;
});
CodingAssistant.displayName = 'CodingAssistant';