services:
  client:
    build:
      context: .
      dockerfile: dockerfile.client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    build: 
      context: .
      dockerfile: dockerfile.server
    container_name: server
    ports:
      - "3001:3001"
    depends_on:
      - client
  